import type { Theme } from "../../types/theme";

export const tabularisDark: Theme = {
  id: "tabularis-dark",
  name: "Mavicat Desktop Dark",
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: "#202020",
      elevated: "#2a2a2a",
      overlay: "#333333",
      input: "#242424",
      tooltip: "#303030",
    },
    surface: {
      primary: "#2d2d2d",
      secondary: "#383838",
      tertiary: "#464646",
      hover: "#3f3f3f",
      active: "#2f7edb",
      disabled: "#292929",
    },
    text: {
      primary: "#f0f0f0",
      secondary: "#c5c5c5",
      muted: "#9298a0",
      disabled: "#686868",
      accent: "#4da0ff",
      inverse: "#111111",
    },
    accent: {
      primary: "#2f7edb",
      secondary: "#7f8cff",
      success: "#29a35a",
      warning: "#d89a2b",
      error: "#d84d4d",
      info: "#36a7c8",
    },
    border: {
      subtle: "#303030",
      default: "#484848",
      strong: "#5d5d5d",
      focus: "#4da0ff",
    },
    semantic: {
      string: "#f87171",
      number: "#60a5fa",
      boolean: "#a78bfa",
      date: "#4ade80",
      null: "#64748b",
      primaryKey: "#fbbf24",
      foreignKey: "#22d3ee",
      index: "#c084fc",
      connectionActive: "#22c55e",
      connectionInactive: "#7b7b7b",
      modified: "#4da0ff",
      deleted: "#ef4444",
      new: "#22c55e",
    },
  },
  typography: {
    fontFamily: {
      base: "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
      mono: "JetBrains Mono, Fira Code, Monaco, Consolas, monospace",
    },
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
    },
  },
  layout: {
    borderRadius: {
      sm: "0.125rem",
      base: "0.25rem",
      lg: "0.375rem",
      xl: "0.5rem",
    },
    spacing: {
      xs: "0.25rem",
      sm: "0.5rem",
      base: "1rem",
      lg: "1.5rem",
      xl: "2rem",
    },
  },
  monacoTheme: {
    base: "vs-dark",
    inherit: true,
    themeName: "GitHub Dark",
  },
};
